@startuml
title CPM - Блок-схема алгоритма критического пути

start
:Получить project_id;
:Загрузить проект, изделия,\nкомпоненты и операции;

if (Операции найдены?) then (да)
  :Построить граф операций (DAG);
  :Топологическая сортировка\n(алгоритм Кана);

  if (Есть цикл в графе?) then (да)
    :Ошибка: CPM требует DAG;
    stop
  else (нет)
    :Прямой проход:\nES/EF для каждой операции;
    :Определить длительность проекта\nmax(EF);
    :Обратный проход:\nLS/LF для каждой операции;
    :Вычислить резерв\nfloat = LS - ES;
    :Выделить критические операции\n(float = 0);
    :Сформировать результат:\ntotal_duration, operations,\ncritical_path;
    stop
  endif
else (нет)
  :Вернуть пустой результат\n(total_duration = 0);
  stop
endif

@enduml
