# Generated by Django 4.2.7 on 2026-02-25 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_name', models.CharField(db_index=True, help_text='Название алгоритма', max_length=255)),
                ('total_duration', models.FloatField(blank=True, help_text='Общая длительность (критерий)', null=True)),
                ('resource_utilization', models.FloatField(blank=True, help_text='Утилизация ресурсов (критерий)', null=True)),
                ('deadline_satisfaction', models.FloatField(blank=True, help_text='Удовлетворение дедлайна (критерий)', null=True)),
                ('computed_date', models.DateField(blank=True, help_text='Дата расчета', null=True)),
            ],
            options={
                'db_table': 'algorithm_comparison',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название компонента', max_length=255)),
                ('type', models.CharField(blank=True, db_index=True, help_text='Тип/класс компонента', max_length=255)),
                ('quantity', models.IntegerField(blank=True, help_text='Количество (шт.)', null=True)),
                ('parameters', models.JSONField(blank=True, help_text='Параметры компонента (JSON)', null=True)),
                ('labor_per_operation', models.DecimalField(blank=True, decimal_places=0, help_text='Трудозатраты на операцию (чел.-часы)', max_digits=19, null=True)),
                ('dependencies', models.JSONField(blank=True, help_text='Технологические/структурные зависимости (JSON)', null=True)),
            ],
            options={
                'db_table': 'component',
            },
        ),
        migrations.CreateModel(
            name='ComponentTechProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'component_tech_process',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название оборудования', max_length=255)),
                ('type', models.CharField(blank=True, db_index=True, help_text='Тип оборудования', max_length=255)),
                ('specifications', models.JSONField(blank=True, help_text='Характеристики (JSON)', null=True)),
                ('work_schedule', models.JSONField(blank=True, help_text='График работы (JSON)', null=True)),
                ('maintenance_requirements', models.CharField(blank=True, help_text='Требования к обслуживанию', max_length=255)),
                ('cost_per_hour', models.DecimalField(blank=True, decimal_places=0, help_text='Стоимость часа эксплуатации', max_digits=19, null=True)),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, help_text='ФИО', max_length=255)),
                ('position', models.CharField(blank=True, db_index=True, help_text='Должность', max_length=255)),
                ('qualification', models.CharField(blank=True, help_text='Квалификация', max_length=255)),
                ('specialization', models.CharField(blank=True, help_text='Специализация', max_length=255)),
                ('work_schedule', models.JSONField(blank=True, help_text='График работы (JSON)', null=True)),
                ('monthly_hours_norm', models.IntegerField(blank=True, help_text='Норма часов в месяц', null=True)),
                ('current_load_percent', models.DecimalField(blank=True, decimal_places=0, help_text='Текущая загрузка (%)', max_digits=19, null=True)),
            ],
            options={
                'db_table': 'personnel',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название изделия', max_length=255)),
                ('code', models.CharField(blank=True, db_index=True, help_text='Код/обозначение', max_length=255)),
                ('type', models.CharField(blank=True, db_index=True, help_text='Тип изделия', max_length=255)),
                ('structure_tree', models.JSONField(blank=True, help_text='Древовидная структура изделия (JSON)', null=True)),
                ('tech_requirements', models.CharField(blank=True, help_text='Технические требования', max_length=255)),
                ('norm_hours', models.DecimalField(blank=True, decimal_places=0, help_text='Нормо-часы на изделие', max_digits=19, null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_used', models.CharField(db_index=True, help_text='Используемый алгоритм', max_length=255)),
                ('created_date', models.DateField(blank=True, help_text='Дата создания', null=True)),
                ('status', models.CharField(db_index=True, help_text='Статус плана', max_length=255)),
                ('schedule', models.JSONField(blank=True, help_text='Расписание (JSON)', null=True)),
                ('actual_data', models.JSONField(blank=True, help_text='Фактические данные (JSON)', null=True)),
                ('deviations', models.JSONField(blank=True, help_text='Отклонения (JSON)', null=True)),
            ],
            options={
                'db_table': 'production_plan',
            },
        ),
        migrations.CreateModel(
            name='TechProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название техпроцесса/операции', max_length=255)),
                ('description', models.CharField(blank=True, help_text='Описание', max_length=255)),
                ('required_qualification', models.CharField(blank=True, help_text='Требуемая квалификация', max_length=255)),
                ('equipment_required', models.JSONField(blank=True, help_text='Требуемое оборудование (JSON)', null=True)),
                ('prep_time', models.IntegerField(blank=True, help_text='Подготовительное время', null=True)),
                ('unit_time', models.IntegerField(blank=True, help_text='Штучное время', null=True)),
                ('sequence_order', models.IntegerField(blank=True, db_index=True, help_text='Порядок выполнения', null=True)),
            ],
            options={
                'db_table': 'tech_process',
                'indexes': [models.Index(fields=['name'], name='tp_name_idx'), models.Index(fields=['sequence_order'], name='tp_seq_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название проекта', max_length=255)),
                ('description', models.CharField(blank=True, help_text='Описание проекта', max_length=255)),
                ('status', models.CharField(db_index=True, help_text='Статус проекта', max_length=255)),
                ('start_date', models.DateField(blank=True, help_text='Дата начала', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Дата окончания (факт)', null=True)),
                ('deadline', models.DateField(blank=True, help_text='Дедлайн (план)', null=True)),
                ('total_labor_planned', models.DecimalField(blank=True, decimal_places=0, help_text='Плановые трудозатраты (чел.-часы)', max_digits=19, null=True)),
                ('total_labor_actual', models.DecimalField(blank=True, decimal_places=0, help_text='Фактические трудозатраты (чел.-часы)', max_digits=19, null=True)),
            ],
            options={
                'db_table': 'project',
                'indexes': [models.Index(fields=['status'], name='project_status_idx'), models.Index(fields=['start_date'], name='project_start_dt_idx'), models.Index(fields=['deadline'], name='project_deadline_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductionPlanPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_assigned', models.IntegerField(blank=True, help_text='Назначенные часы', null=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.personnel')),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.productionplan')),
            ],
            options={
                'db_table': 'production_plan_personnel',
            },
        ),
        migrations.CreateModel(
            name='ProductionPlanEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_required', models.IntegerField(blank=True, help_text='Требуемые часы', null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.equipment')),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.productionplan')),
            ],
            options={
                'db_table': 'production_plan_equipment',
            },
        ),
        migrations.AddField(
            model_name='productionplan',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='production_plans', through='planner.ProductionPlanEquipment', to='planner.equipment'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='personnel',
            field=models.ManyToManyField(blank=True, related_name='production_plans', through='planner.ProductionPlanPersonnel', to='planner.personnel'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='planner.project'),
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.component')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.product')),
            ],
            options={
                'db_table': 'product_component',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='products_m2m', through='planner.ProductComponent', to='planner.component'),
        ),
        migrations.AddField(
            model_name='product',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='planner.project'),
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['full_name'], name='pers_name_idx'),
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['position'], name='pers_pos_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['name'], name='equip_name_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['type'], name='equip_type_idx'),
        ),
        migrations.AddField(
            model_name='componenttechprocess',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.component'),
        ),
        migrations.AddField(
            model_name='componenttechprocess',
            name='tech_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.techprocess'),
        ),
        migrations.AddField(
            model_name='component',
            name='parent_component',
            field=models.ForeignKey(blank=True, help_text='Родительский компонент (для иерархии)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='planner.component'),
        ),
        migrations.AddField(
            model_name='component',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components_fk', to='planner.product'),
        ),
        migrations.AddField(
            model_name='component',
            name='tech_processes',
            field=models.ManyToManyField(blank=True, related_name='components', through='planner.ComponentTechProcess', to='planner.techprocess'),
        ),
        migrations.AddField(
            model_name='algorithmcomparison',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algorithm_comparisons', to='planner.project'),
        ),
        migrations.AddIndex(
            model_name='productionplanpersonnel',
            index=models.Index(fields=['production_plan'], name='ppp_plan_idx'),
        ),
        migrations.AddIndex(
            model_name='productionplanpersonnel',
            index=models.Index(fields=['personnel'], name='ppp_personnel_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionplanpersonnel',
            constraint=models.UniqueConstraint(fields=('production_plan', 'personnel'), name='uq_plan_personnel'),
        ),
        migrations.AddIndex(
            model_name='productionplanequipment',
            index=models.Index(fields=['production_plan'], name='ppe_plan_idx'),
        ),
        migrations.AddIndex(
            model_name='productionplanequipment',
            index=models.Index(fields=['equipment'], name='ppe_equipment_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionplanequipment',
            constraint=models.UniqueConstraint(fields=('production_plan', 'equipment'), name='uq_plan_equipment'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['project', 'status'], name='plan_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['project', 'created_date'], name='plan_proj_created_idx'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['algorithm_used'], name='plan_algo_idx'),
        ),
        migrations.AddIndex(
            model_name='productcomponent',
            index=models.Index(fields=['product'], name='pc_product_idx'),
        ),
        migrations.AddIndex(
            model_name='productcomponent',
            index=models.Index(fields=['component'], name='pc_component_idx'),
        ),
        migrations.AddConstraint(
            model_name='productcomponent',
            constraint=models.UniqueConstraint(fields=('product', 'component'), name='uq_product_component'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['project', 'name'], name='product_proj_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['project', 'code'], name='product_proj_code_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['type'], name='product_type_idx'),
        ),
        migrations.AddIndex(
            model_name='componenttechprocess',
            index=models.Index(fields=['component'], name='ctp_component_idx'),
        ),
        migrations.AddIndex(
            model_name='componenttechprocess',
            index=models.Index(fields=['tech_process'], name='ctp_techproc_idx'),
        ),
        migrations.AddConstraint(
            model_name='componenttechprocess',
            constraint=models.UniqueConstraint(fields=('component', 'tech_process'), name='uq_component_tech_process'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['product', 'name'], name='comp_prod_name_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['product', 'type'], name='comp_prod_type_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['parent_component'], name='comp_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='algorithmcomparison',
            index=models.Index(fields=['project', 'algorithm_name'], name='algo_proj_name_idx'),
        ),
        migrations.AddIndex(
            model_name='algorithmcomparison',
            index=models.Index(fields=['computed_date'], name='algo_comp_dt_idx'),
        ),
    ]
